### ISSUE TITLE
Warnings when using the plugin with Typescript

### ISSUE THREAD

**Issue by felixranesberger** [s2b/vite-plugin-auto-origin#1]
Hi Simon, I'm already using your plugin 👍 

When using the package, I'm getting two warnings / errors:

This could be a configuration issue in the package.json?
Maybe `type="module"` missing?
<img width="1250" alt="Screenshot 2023-10-16 at 08 27 50" src="https://github.com/s2b/vite-plugin-auto-origin/assets/52704891/d4d73e40-2283-494f-bd98-43432722e93a">

Package types seem to be not working:
<img width="724" alt="Screenshot 2023-10-16 at 08 27 58" src="https://github.com/s2b/vite-plugin-auto-origin/assets/52704891/f7571e63-ecbf-4492-8f29-fd58c8df064d">

If I have time, I try to provide a pull request, fixing the issue.
But I wanted to keep track of the errors as a issue.

Thanks for your work!

**Comment by s2b** [comment]
v1.0.2 should now contain correct typescript definitions.
